"""Agent Core：对话循环、LLM 调用、tool dispatch。"""

from .llm import get_llm_client
from .loop import run_chat_loop
from .persistence import (
    append_message,
    build_llm_messages,
    create_response,
    create_run,
    create_session,
    create_attachment,
    delete_session,
    expire_stale_runs,
    get_active_run,
    get_last_user_message,
    get_response,
    get_response_session_id,
    get_session_system_prompt,
    list_messages,
    list_sessions,
    link_message_attachments,
    get_attachments_by_ids,
    persist_openai_message,
    persist_context_compression,
    session_lock,
    set_session_system_prompt,
    truncate_after_last_user,
    update_message,
    update_run,
    upsert_session_meta,
)
from .run_manager import ERROR, FINISHED, cancel_active_run, start_stream_run
from .session_title import maybe_generate_and_update_session_title

__all__ = [
    "append_message",
    "build_llm_messages",
    "create_response",
    "create_run",
    "create_session",
    "create_attachment",
    "delete_session",
    "expire_stale_runs",
    "get_active_run",
    "get_last_user_message",
    "get_response",
    "get_response_session_id",
    "get_session_system_prompt",
    "get_llm_client",
    "list_messages",
    "list_sessions",
    "link_message_attachments",
    "get_attachments_by_ids",
    "persist_openai_message",
    "persist_context_compression",
    "run_chat_loop",
    "session_lock",
    "set_session_system_prompt",
    "truncate_after_last_user",
    "update_message",
    "update_run",
    "upsert_session_meta",
    "start_stream_run",
    "cancel_active_run",
    "maybe_generate_and_update_session_title",
]
